name: &name 'welcome'
controller: experiment_action_controller
start_dt: 2019-09-23
end_dt: 2020-09-23
settings:
  intervention_name: *name
  intervention_type: 'welcome'
#  randomizations_file: fr-dummy-randomziation-20190924-100000.json
#  randomizations_file: fr-dummy-randomziation-20190924-10000.json
  randomizations_file: fr-dummy-randomziation-20190924-100000.split.noindex.json
  units_per_block: 3

dirs:
  project: /data/project/frwelcome
  randomizations: randomizations
