name: &name 'fr_wiki_welcome'
controller: experiment_action_controller
control_action_is_skip: True # means that randomization_arm=0 is to do nothing.
start_dt: 2019-09-23
end_dt: 2020-09-23
settings:
  intervention_name: 'fr_wiki_welcome_survey'
  intervention_type: 'talk_page_message'

survey_settings:
  survey_after_days: 84
  survey_after_intervention: 'welcome'
  survey_after_intervention_type: 'talk_page_message'
  #  max_surveys: 6000

message_settings:
  seciton: new
  skip_words:
    - qualtrics
  check_blocked: True
  check_uncreated: False

dirs:
  project: /data/project/frwelcome
  randomizations: randomizations
  reports: reports

reports:
  email_subject: "fr welcome"
  from_addr: 'system.operations@civilservant.io'
  to_addrs:
    - max.klein@civilservant.io
    - julia.kamin@civilservant.io
    - eric.pennington@civilservant.io
