name: &name 'fr_wiki_welcome'
controller: experiment_action_controller
start_dt: 2019-09-23
end_dt: 2020-09-23
settings:
  intervention_name: *name
  intervention_type: 'welcome'
#  randomizations_file: fr-dummy-randomziation-20190924-100000.json
#  randomizations_file: fr-dummy-randomziation-20190924-10000.json
#  randomizations_file: fr-dummy-randomziation-20190924-100000.split.noindex.json
  randomizations_file: fr-randomziation-20191015-100000-60upb.split.noindex.json
  units_per_block: 60
  randomization_obfuscations_file: fr-obfuscations.json

message_settings:
  seciton: null
  skip_words: ['civilservant', 'loveless', 'bienvenue']
  check_blocked: True
  check_uncreated: True

dirs:
  project: /data/project/frwelcome
  randomizations: randomizations

